// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/player/:playerId": {
    params: {
      "playerId": string;
    };
  };
  "/webhooks/update": {
    params: {};
  };
  "/webhooks/wipe": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/player/:playerId" | "/webhooks/update" | "/webhooks/wipe";
  };
  "routes/api.player.$playerId.ts": {
    id: "routes/api.player.$playerId";
    page: "/api/player/:playerId";
  };
  "routes/webhooks.update.ts": {
    id: "routes/webhooks.update";
    page: "/webhooks/update";
  };
  "routes/webhooks.wipe.ts": {
    id: "routes/webhooks.wipe";
    page: "/webhooks/wipe";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};